### ISSUE TITLE
✨ Allow using regular expressions in string matching

### ISSUE THREAD

**Issue by aslilac** [ren-lang/compiler#107]
Something like `"/user/{user_id:/\w+/}/post/{post_id:/\w+/}"`

**Comment by hayleigh-dot-dev** [comment]
So I think we have three options here:

- Preserve the current behaviour and make clear in the language docs that this is a greedy pattern.
- Do the opposite: make the pattern non-greedy and communicate that behaviour.
- Do what is proposed here and allow user-defined regex.
    - There's another question here about do we allow no regex to be supplied? If so, which of the above behaviours do we fallback to?

I'm inclined _not_ to go with the proposed (I know I told you to open the issue) but I'd like to hear everyone's thoughts first. @Alpvax @Trymunx what do you think?

**Comment by Alpvax** [comment]
I feel that if we're going with regex, we should just go with regex (and encourage the use of named capture groups), rather than some halfway template regex thing.

Either we add regex matching or we just have a modifier (probably `?`) to indicate non-greedy. I personally like the regex approach, as it's more powerful, but I don't think we should have a weird combination.
